### ISSUE TITLE
CI testing 'headless'

### ISSUE THREAD

**Issue by jdha** [pyNEMO/nml_meld#7]
Work out how to setup unit tests under CI in 'headless' mode in order to handle the GUI

**Comment by jdha** [comment]
perhaps the following will allow headless tests:

```
- name: Run headless test
  uses: GabrielBB/xvfb-action@v1
  with:
    run: npm test
```

need to explore further
